#################
### AUTOSTART ###
#################

exec-once = waybar
exec-once = hyprpaper
exec-once = swaync

# GTK FileChooser
exec-once = gsettings set org.gtk.Settings.FileChooser window-size '(1080, 720)'
exec-once = gsettings set org.gtk.gtk4.Settings.FileChooser window-size '(1080, 720)'

# GTK Theme
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Tokyonight-Dark"
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

# Launcher
exec-once = elephant
exec-once = walker --gapplication-service
