
# BACKGROUND
background {
    monitor = HDMI-A-6
    path = $HOME/Images/Wallpapers/Ekko_Powder.jpg
    blur_passes = 0
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

background {
    monitor = HDMI-A-5
    path = $HOME/Images/Wallpapers/Ekko_Powder.jpg
    blur_passes = 0
    blur_size = 0
    contrast = 1.0
    brightness = 1.0
    vibrancy = 0.5
    vibrancy_darkness = 0.0
}

# GENERAL
general {
}


# Time
label {
    monitor = HDMI-A-6
    text = cmd[update:1000] echo -e "$(date +"%H:%M")"
    color = rgba(216, 222, 233, 1.0)
    font_size = 99
    font_family = ArcadeClassic
    position = 0, 440
    halign = center
    valign = center
}

# Date-Month
label {
    monitor = HDMI-A-6
    text = cmd[update:1000] echo -e "$(date +"%d  %B")"
    color = rgba(216, 222, 233, 1.0)
    font_size = 22
    font_family = ArcadeClassic
    position = 0, 340
    halign = center
    valign = center
}


# USER-BOX
shape {
    monitor = HDMI-A-6
    size = 512, 33
    color = rgba(240, 240, 240, .15)
    rounding = 20
    border_size = 0
    border_color = rgba(240, 240, 240, 0)
    rotate = 0
    xray = false

    position = 0, -40
    halign = center
    valign = center
}

# USER
label {
    monitor = HDMI-A-6
    text =     $USER
    color = rgba(216, 222, 233, 1.0)
    font_size = 11
    font_family = ArcadeClassic
    position = 0, -40
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor = HDMI-A-6
    size = 512, 33
    outline_thickness = 0
    dots_size = 0.15 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(240, 240, 240, 0)
    inner_color = rgba(240, 240, 240, .15)
    font_color = rgb(240, 240, 240)
    fade_on_empty = false
    font_size = 11
    font_family = ArcadeClassic
    placeholder_text = <span foreground="##f0f0f0b3" font_size="11pt"> mot de passe</span>
    hide_input = false
    rounding = 20
    position = 0, -88
    halign = center
    valign = center
}

# Reboot
label {
    monitor = HDMI-A-6
    text = 󰜉
    color = rgba(240, 240, 240, 0.6)
    font_size = 50
    font_family = JetBrainsMono Nerd Font
    onclick = reboot now
    position = 0, 60
    halign = center
    valign = bottom
}
# Power off
label {
    monitor = HDMI-A-6
    text = 󰐥
    color = rgba(240, 240, 240, 0.6)
    font_size = 50
    font_family = JetBrainsMono Nerd Font
    onclick = shutdown now
    position = 6%, 60
    halign = center
    valign = bottom
}
# Suspend
label {
    monitor = HDMI-A-6
    text = 󰤄
    color = rgba(240, 240, 240, 0.6)
    font_size = 50
    font_family = JetBrainsMono Nerd Font
    onclick = systemctl suspend
    position = -6%, 60
    halign = center
    valign = bottom
}
